/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_EXAMPLESB_CAPI_TEST_B_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_EXAMPLESB_CAPI_TEST_B_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/examplesB/CAPITestBStub.hpp>
#include <v1/commonapi/examplesB/CAPITestBSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace examplesB {

template <typename _Stub = ::v1::commonapi::examplesB::CAPITestBStub, typename... _Stubs>
class CAPITestBSomeIPStubAdapterInternal
    : public virtual CAPITestBStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< CAPITestBSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> CAPITestBSomeIPStubAdapterHelper;

    ~CAPITestBSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        CAPITestBSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::examplesB::CAPITestBStub,
        CommonAPI::Version
    > getCAPITestBInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::examplesB::CAPITestBStub,
        std::tuple< int32_t>,
        std::tuple< CAPITestB::stdErrorTypeEnum, int32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< ::v1::commonapi::examplesB::CAPITestB_::stdErrorTypeEnumDeployment_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>>
    > fooStubDispatcher;
    
    CAPITestBSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        CAPITestBSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< CAPITestBStub>(_stub)),
        getCAPITestBInterfaceVersionStubDispatcher(&CAPITestBStub::lockInterfaceVersionAttribute, &CAPITestBStub::getInterfaceVersion, false, true),
        fooStubDispatcher(
            &CAPITestBStub::foo,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::examplesB::CAPITestB_::stdErrorTypeEnumDeployment_t * >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
        
    {
        CAPITestBSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7530) }, &fooStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void CAPITestBSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void CAPITestBSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::examplesB::CAPITestBStub, typename... _Stubs>
class CAPITestBSomeIPStubAdapter
    : public CAPITestBSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    CAPITestBSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          CAPITestBSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace examplesB
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_EXAMPLESB_CAPI_Test_B_SOMEIP_STUB_ADAPTER_HPP_
