/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/examplesA/CAPITestASomeIPStubAdapter.hpp>
#include <v1/commonapi/examplesA/CAPITestA.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace examplesA {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createCAPITestASomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< CAPITestASomeIPStubAdapter<::v1::commonapi::examplesA::CAPITestAStub>>(_address, _connection, _stub);
}

void initializeCAPITestASomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.examplesA.CAPITestA:v1_2:commonapi.examplesA.Methods",
         0x1234, 0x5678, 1, 2);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "commonapi.examplesA.CAPITestA:v1_2",
        &createCAPITestASomeIPStubAdapter);
}

INITIALIZER(registerCAPITestASomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeCAPITestASomeIPStubAdapter);
}

} // namespace examplesA
} // namespace commonapi
} // namespace v1
